Added error checking logic for retrieval

diff --git a/.sti/bin/assemble b/.sti/bin/assemble
--- a/.sti/bin/assemble
+++ b/.sti/bin/assemble
@@ -82,6 +82,11 @@ if [ ! -z "${SRC_APP_URL}" ]; then
  
  curl -L -fs -o "${DEPLOY_DIR}/${SRC_APP_NAME}" "${SRC_APP_URL}"
  
+ if [ $? -ne 0 ]; then
+   echo "Error retrieving packaged application due to error code $ERR"
+   exit $ERR
+ fi
+ 
 fi
 
 
